# Generated by Django 5.2 on 2025-12-16 16:36

import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("answer", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Collection",
            fields=[
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=50, verbose_name="收藏夹标题")),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="收藏夹简介"),
                ),
                (
                    "is_public",
                    models.BooleanField(default=True, verbose_name="收藏夹是否公开"),
                ),
                (
                    "answers",
                    models.ManyToManyField(
                        blank=True,
                        related_name="collections",
                        to="answer.answer",
                        verbose_name="收藏的内容(回答)",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="owned_collections",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="收藏夹创建者",
                    ),
                ),
            ],
            options={
                "verbose_name": "收藏夹",
                "verbose_name_plural": "收藏夹",
                "db_table": "collection",
                "ordering": ["-created"],
            },
        ),
    ]
