# Generated by Django 5.2 on 2025-12-25 16:49

import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("comment", "0001_initial"),
        ("vote", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="answervote",
            name="vote_type",
            field=models.SmallIntegerField(
                choices=[(1, "赞同"), (-1, "不赞同/反对"), (0, "取消投票/未投票")],
                default=1,
                verbose_name="投票类型",
            ),
        ),
        migrations.AlterField(
            model_name="questionvote",
            name="vote_type",
            field=models.SmallIntegerField(
                choices=[(1, "赞同"), (-1, "不赞同/反对"), (0, "取消投票/未投票")],
                default=1,
                verbose_name="投票类型",
            ),
        ),
        migrations.CreateModel(
            name="CommentVote",
            fields=[
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "vote_type",
                    models.SmallIntegerField(
                        choices=[(1, "赞同"), (-1, "不赞同/反对"), (0, "取消投票/未投票")],
                        default=1,
                        verbose_name="投票类型",
                    ),
                ),
                (
                    "comment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="votes",
                        to="comment.comment",
                        verbose_name="所属评论",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="投票用户",
                    ),
                ),
            ],
            options={
                "verbose_name": "评论投票",
                "verbose_name_plural": "评论投票",
                "db_table": "vote_comment",
                "unique_together": {("user", "comment")},
            },
        ),
    ]
