# Generated by Django 5.2 on 2025-12-16 16:03

import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("topic", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Question",
            fields=[
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="问题标题")),
                (
                    "content",
                    models.TextField(blank=True, null=True, verbose_name="问题内容"),
                ),
                (
                    "view_count",
                    models.PositiveIntegerField(default=0, verbose_name="浏览量"),
                ),
                (
                    "followers",
                    models.ManyToManyField(
                        blank=True,
                        related_name="followed_questions",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="关注者",
                    ),
                ),
                (
                    "questioner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="questions",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="提问者",
                    ),
                ),
                (
                    "topics",
                    models.ManyToManyField(
                        blank=True,
                        related_name="questions",
                        to="topic.topic",
                        verbose_name="关联话题",
                    ),
                ),
            ],
            options={
                "verbose_name": "问题",
                "verbose_name_plural": "问题",
                "db_table": "question",
                "ordering": ["-created"],
            },
        ),
    ]
