"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.2.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os
from datetime import timedelta

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# 确保项目根目录下存在 logs 文件夹，否则 FileHandler 会报错
LOG_DIR = BASE_DIR / 'logs'
if not LOG_DIR.exists():
    os.makedirs(LOG_DIR)

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "django-insecure-i#us65davk)kpoll&-@ql4s)&&x-t5&m57%aa_(h!^=c!r#%15"

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = [
    '127.0.0.1',
    '0.0.0.0',
    'localhost',
]

# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "corsheaders",
    "rest_framework_simplejwt",
    "model_utils",
    "django_filters",
    "rest_framework",

    # local apps:
    "base.apps.BaseConfig",
    "chat.apps.ChatConfig",
    "collection.apps.CollectionConfig",
    "topic.apps.TopicConfig",
    "question.apps.QuestionConfig",
    "answer.apps.AnswerConfig",
    "vote.apps.VoteConfig",
    "comment.apps.CommentConfig",
]

MIDDLEWARE = [
    "corsheaders.middleware.CorsMiddleware",
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "config.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "config.wsgi.application"

# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': os.getenv("HUZHI_MYSQL_NAME"),  # 数据库名
        'USER': os.getenv("HUZHI_MYSQL_USER"),  # 用户
        'PASSWORD': os.getenv("HUZHI_MYSQL_PASSWORD"),  # 密码
        'HOST': os.getenv("HUZHI_MYSQL_HOST"),  # 地址
        'PORT': os.getenv("HUZHI_MYSQL_PORT"),  # 端口
        # 单元测试数据库
        'TEST': {
            'NAME': '',  # 使用固定的单元测试数据库，保持与主库同步
        }
    }
}

# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]

# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

AUTH_USER_MODEL = 'base.User'

# 腾讯云COS配置
COS_SECRET_ID = os.getenv("COS_SECRET_ID")
COS_SECRET_KEY = os.getenv("COS_SECRET_KEY")
COS_BUCKET = os.getenv("COS_BUCKET")
COS_REGION = os.getenv("COS_REGION")

# 暴露需要的Header
CORS_EXPOSE_HEADERS = [
    'Content-Disposition',  # 主要用于文件下载
]

# 允许所有来源
CORS_ALLOW_ALL_ORIGINS = True

# 关闭凭证允许
CORS_ALLOW_CREDENTIALS = False  # 使用jwt,前端通过 Header (Authorization: Bearer <token>) 传 Token，不需要开启

LANGUAGE_CODE = "zh-hans"

TIME_ZONE = "Asia/Shanghai"

USE_I18N = True

USE_L10N = True

USE_TZ = False

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = "static/"

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# DRF配置
REST_FRAMEWORK = {
    'EXCEPTION_HANDLER': 'common.exceptions.custom_exception_handler',
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
}

# JWT配置
SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(hours=10),
    "REFRESH_TOKEN_LIFETIME": timedelta(days=7),
}

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,

    'formatters': {
        # 详细格式：包含时间、日志级别、进程ID、线程ID、文件名、行号、信息
        'verbose': {
            'format': '{levelname} {asctime} {module} {process:d} {thread:d} {message}',
            'style': '{',
        },
        # 简单格式：只包含时间、级别、模块名、信息（适合控制台）
        'simple': {
            'format': '{levelname} {asctime} {module}: {message}',
            'style': '{',
        },
    },

    'filters': {
        # 过滤器：只有在 DEBUG = True 时通过（用于控制台）
        'require_debug_true': {
            '()': 'django.utils.log.RequireDebugTrue',
        },
        # 过滤器：只有在 DEBUG = False 时通过（用于文件）
        'require_debug_false': {
            '()': 'django.utils.log.RequireDebugFalse',
        },
    },

    'handlers': {
        # 控制台：只在开发模式(DEBUG=True)下生效
        'console': {
            'level': 'DEBUG',  # 开发时想看尽可能详细的信息
            'filters': ['require_debug_true'],
            'class': 'logging.StreamHandler',
            'formatter': 'simple',
        },
        # 文件：只在生产模式(DEBUG=False)下生效
        'file': {
            'level': 'INFO',
            'filters': ['require_debug_false'],  # 开发时这里会被阻断，不会创建/写入文件
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': LOG_DIR / 'info.log',
            'maxBytes': 1024 * 1024 * 10,
            'backupCount': 10,
            'formatter': 'verbose',
            'encoding': 'utf-8',
            'delay': True,
        },
        'error_file': {
            'level': 'ERROR',
            'filters': ['require_debug_false'],
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': LOG_DIR / 'error.log',
            'maxBytes': 1024 * 1024 * 10,
            'backupCount': 5,
            'formatter': 'verbose',
            'encoding': 'utf-8',
            'delay': True,
        },
    },

    'loggers': {
        'django': {
            'handlers': ['console', 'file', 'error_file'],
            'level': 'INFO',
            'propagate': True,
        },
        # 捕获所有 App 的日志
        '': {  # 空字符串代表“根记录器”(Root Logger)
            'handlers': ['console', 'file', 'error_file'],
            'level': 'DEBUG',
        },
        # 调试时控制台打印sql语句
        'django.db.backends': {
            'handlers': ['console'],
            'level': 'DEBUG',
            'propagate': False,
        },
    },
}
