# 错误码定义
COLLECTION_NOT_FOUND = 70001
COLLECTION_PERMISSION_DENIED = 70002
COLLECTION_NOT_OWNER = 70003

# 错误消息
COLLECTION_NOT_FOUND_MSG = "收藏夹不存在"
COLLECTION_PERMISSION_DENIED_MSG = "无权限访问该收藏夹"
COLLECTION_NOT_OWNER_MSG = "只有收藏夹所有者才能执行此操作"
