CONTENT_AUDIT_REJECTED = 90001  # 内容审核未通过
CONTENT_AUDIT_FAILED = 90002  # 内容审核服务调用失败

CONTENT_AUDIT_REJECTED_MSG = "内容涉嫌违规，请修改后重试"
CONTENT_AUDIT_FAILED_MSG = "内容安全校验失败，请稍后重试"

CONTENT_SAFETY_SUGGESTION_PASS = "Pass"
CONTENT_SAFETY_SUGGESTION_REVIEW = "Review"
CONTENT_SAFETY_SUGGESTION_BLOCK = "Block"
