# Generated by Django 5.2 on 2026-01-27 21:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="cover_image",
            field=models.URLField(
                blank=True, max_length=500, null=True, verbose_name="封面背景图URL"
            ),
        ),
    ]
