# 密码复杂度校验正则
PASSWORD_PATTERN = r'^(?=.*[a-z])(?=.*[A-Z])(?=.*\d).{8,}$'

# 错误码定义
PASSWORD_FORMAT_ERROR = 10001  # 密码格式错误
USER_NOT_FOUND = 10002  # 用户不存在
PASSWORD_INCORRECT = 10003  # 密码错误
INVALID_TOKEN = 10004  # 无效token
CODE_SEND_TOO_FREQUENT = 10005  # 验证码发送过于频繁
INVALID_VERIFY_CODE = 10006  # 验证码无效或已过期
EMAIL_SEND_FAILED = 10007  # 邮件发送失败
USERNAME_ALREADY_EXISTS = 10008  # 用户名已存在
EMAIL_ALREADY_EXISTS = 10009  # 邮箱已存在
PHONE_ALREADY_EXISTS = 10010  # 手机号已存在
CANNOT_FOLLOW_SELF = 10011  # 不能关注自己
NOTIFICATION_NOT_FOUND = 10012  # 通知不存在
USER_DISABLED = 10013  # 用户已被封禁

# 错误消息
PASSWORD_FORMAT_ERROR_MSG = "密码需包含大小写字母和数字，长度至少8位"
USER_NOT_FOUND_MSG = "用户不存在"
PASSWORD_INCORRECT_MSG = "密码错误"
INVALID_TOKEN_MSG = "无效的token"
CODE_SEND_TOO_FREQUENT_MSG = "验证码发送过于频繁，请稍后再试"
INVALID_VERIFY_CODE_MSG = "验证码无效或已过期"
EMAIL_SEND_FAILED_MSG = "邮件发送失败，请稍后重试"
USERNAME_ALREADY_EXISTS_MSG = "该用户名已被使用"
EMAIL_ALREADY_EXISTS_MSG = "该邮箱已被使用"
PHONE_ALREADY_EXISTS_MSG = "该手机号已被使用"
CANNOT_FOLLOW_SELF_MSG = "不能关注自己"
NOTIFICATION_NOT_FOUND_MSG = "通知不存在"
USER_DISABLED_MSG = "账号已被封禁，请联系管理员"

# 用户关注操作常量
USER_FOLLOW_ACTION = 1  # 关注
USER_UNFOLLOW_ACTION = 2  # 取消关注

USER_FOLLOW_ACTION_CHOICES = (
    (USER_FOLLOW_ACTION, '关注'),
    (USER_UNFOLLOW_ACTION, '取消关注'),
)

# 系统通知类型
NOTIFICATION_TYPE_QUESTION_ANSWERED = 1  # 我的提问有人回答
NOTIFICATION_TYPE_ANSWER_UPVOTED = 2  # 我的回答有人点赞
NOTIFICATION_TYPE_COMMENT_REPLIED = 3  # 我的评论有人回复
NOTIFICATION_TYPE_USER_FOLLOWED = 4  # 有人关注我

NOTIFICATION_TYPE_CHOICES = (
    (NOTIFICATION_TYPE_QUESTION_ANSWERED, '我的提问有人回答'),
    (NOTIFICATION_TYPE_ANSWER_UPVOTED, '我的回答有人点赞'),
    (NOTIFICATION_TYPE_COMMENT_REPLIED, '我的评论有人回复'),
    (NOTIFICATION_TYPE_USER_FOLLOWED, '有人关注我'),
)

# Redis Key前缀
REDIS_KEY_PWD_RESET_CODE = "pwd_reset_code:"  # 密码重置验证码
REDIS_KEY_PWD_RESET_LIMIT = "pwd_reset_limit:"  # 密码重置限流
