# Generated by Django 5.2 on 2025-12-22 18:17

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("topic", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="topic",
            name="creator",
            field=models.ForeignKey(
                default=uuid.UUID('00000000-0000-0000-0000-000000000001'),
                on_delete=django.db.models.deletion.CASCADE,
                related_name="created_topics",
                to=settings.AUTH_USER_MODEL,
                verbose_name="创建者",
            ),
            preserve_default=False,
        ),
    ]
